#!/bin/bash
# Test script to drive the example external remote

set -eu -o pipefail -x

externaltype=directory
#
workdir=$(realpath "$(dirname "$0")")
TMP="$(mktemp -d "${TMPDIR:-/tmp}/gar-XXXXXXX")"
REMOTE_DIR="$TMP/remote"
REPO_DIR="$TMP/repo"
mkdir -p "$REMOTE_DIR"
mkdir -p "$REPO_DIR"

# so there is no global git config side-effects
export HOME="$TMP"
git config user.email "someuser@gmail.com"
git config user.name "Some User"

git-annex-remote-$externaltype < /dev/null | grep VERSION

cd "$REPO_DIR"
git init
git annex init
git annex initremote --verbose --debug ${externaltype}_remote type=external externaltype=$externaltype encryption=none directory="$REMOTE_DIR"
git annex testremote --verbose --debug ${externaltype}_remote 2>"$workdir/testremote-$externaltype.err" | tee "$workdir/testremote-$externaltype.out"
